Repository aeternity/elixir-node, pull requests merged in 2018-11, with the labels that each got.

#717 [GH-716] moved environment variable reading from config to code
  .dockerignore
  Dockerfile
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/config/dev_build.exs
  apps/aecore/config/prod.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore/chain/genesis.ex
  apps/aecore/lib/aecore/keys/keys.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/peers/worker/supervisor.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/pow.ex
  apps/aecore/test/aecore_channels_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aehttpserver/config/config.exs
  apps/aehttpserver/config/dev.exs
  apps/aehttpserver/config/prod.exs
  apps/aehttpserver/config/test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/peers_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/endpoint.ex
  apps/aetestframework/lib/worker.ex
  apps/aeutil/lib/environment.ex
Labels: 0.16, bug

#708 [GH-705] Contracts usage documentation
  .iex.exs
  apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
  docs/aeternity-erlang-compatibility.md
  docs/detailed-usage.md
Labels: 0.16, aevm, documentation

#749 [GH-712] Test contracts compatibility with epoch
  apps/aecore/lib/aecore/contract/contract_state_tree.ex
  apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
  apps/aecore/test/aecore_contract_test.exs
  apps/aevm/lib/state.ex
Labels: aevm, bug

#775 [GH-725] Micro block and header structures
  apps/aecore/lib/aecore/chain/micro_block.ex
  apps/aecore/lib/aecore/chain/micro_header.ex
Labels: latest-compatibility, ng-consensus, structures

#774 [GH-724] Key block and header structures, header serialization
  apps/aecore/lib/aecore/chain/key_block.ex
  apps/aecore/lib/aecore/chain/key_header.ex
Labels: latest-compatibility, ng-consensus, structures

#779 [GH-778] Add dependencies to release notes
  docs/release-notes/release-notes-0.1.0.md
Labels: 0.16

#782 [GH-748] Upgraded IDNA library and adjusted NameUtil module
  apps/aecore/lib/aecore/naming/name_util.ex
  mix.exs
  mix.lock
Labels: latest-compatibility, spec-adjust

#783 [GH-746] Restricted registrars in Naming Service
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/test/aecore_naming_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aetestframework/lib/utils.ex
  docs/aeternity-erlang-compatibility.md
  docs/detailed-usage.md
Labels: latest-compatibility, spec-adjust

#785 [GH-738] Added identifiers to both Name and NameCommitment structures
  apps/aecore/lib/aecore/naming/name.ex
  apps/aecore/lib/aecore/naming/name_commitment.ex
Labels: blocked

#789 [GH-755] ChannelStateOnChain adjustments
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutual_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/test/aecore_channels_compatibility_test.exs
Labels: channel

#786 [GH-726] NG mining
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/genesis.ex
  apps/aecore/lib/aecore/chain/key_header.ex
  apps/aecore/lib/aecore/chain/micro_header.ex
  apps/aecore/lib/aecore/chain/target.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/lib/aecore/governance/genesis_constants.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/mock.ex
  apps/aecore/lib/aecore/pow/pow.ex
  apps/aecore/lib/aecore/util/header.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_validation_test.exs
Labels: latest-compatibility, ng-consensus

#784 [GH-735] Adjusted commitment hash function
  apps/aecore/lib/aecore/naming/name_commitment.ex
Labels: latest-compatibility

#794 [GH-733] Implemented garbage collection function for transactions pool
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/priv/genesis/accounts.json
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/test_utils.ex
  apps/aetestframework/lib/utils.ex
  apps/aetestframework/test/multi_node_sync_test.exs
Labels: enhancement

#799 [GH-758] ChannelMutalClose + ChannelSettle adjustments
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutual_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_deposit_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_snapshot_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_withdraw_tx.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_channels_test.exs
  apps/aeutil/lib/type_to_tag.ex
Labels: blocked, channel

#800 [GH-795] Added response TTL to oracle_response_tx
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/oracle_query.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/oracle_controller.ex
  apps/aetestframework/lib/utils.ex
  apps/aetestframework/test/multi_node_sync_test.exs
Labels: latest-compatibility, spec-adjust, structures

#792 [GH-727] Block validation
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/key_block.ex
  apps/aecore/lib/aecore/chain/key_header.ex
  apps/aecore/lib/aecore/chain/micro_block.ex
  apps/aecore/lib/aecore/chain/target.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/pow/pow.ex
Labels: latest-compatibility, ng-consensus

#806 [GH-803] Added release notes for 0.2.0
  docs/release-notes/release-notes-0.2.0.md
Labels: documentation

#808 added disclaimer in readme and updated version
  README.md
  mix.exs
Labels: documentation

#811 [GH-810] Adjust get block by height for KeyBlocks
  apps/aecore/lib/aecore/chain/worker.ex
Labels: ng-consensus
