Repository aeternity/elixir-node, pull requests merged in 2018-03, with the labels that each got.

#201 [GH-#132] Finished integrating the elixir-wallet repository
  Dockerfile
  README.md
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore.ex
  apps/aecore/lib/aecore/keys/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/lib/aecore/wallet/worker/supervisor.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_keys_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/config/config.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
  mix.exs
  mix.lock
Labels: enhancement

#276 [GH-#266] fixed compiler warnings
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/structures/block.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aecore/lib/aecore/wallet/worker.ex
Labels: enhancement, non-spec

#272 [GH-#271] make ci fail on compiler warnings
  .travis.yml
Labels: enhancement, non-spec

#263 [GH-#203] Transaction building structure refactor
  README.md
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/hashcash.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/block.ex
  apps/aecore/lib/aecore/structures/data_tx.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
  apps/aecore/lib/aecore/structures/transaction.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_difficulty_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/config/dev.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/new_tx_controller.ex
  apps/aeutil/lib/bits.ex
  apps/aeutil/lib/parser.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
  mix.lock
Labels: enhancement, non-spec

#236 [GH-234] Added fast get_block_by_height to Chain
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/test/aecore_chain_test.exs
Labels: enhancement, non-spec

#289 [GH-#262] Removed lock_time_block and locked fields
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/data_tx.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
  apps/aecore/lib/aecore/structures/transaction.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_state_test.exs.bak
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: chain-state, spec-adjust

#279 [GH-#278] removed unused plug from endpoint, log to debug
  apps/aehttpserver/lib/aehttpserver/web/endpoint.ex
Labels: enhancement, non-spec

#290 [GH-#256] Adjusted block, header encodings
  .mix.lock.swp
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/config/dev1.exs
  apps/aecore/config/dev2.exs
  apps/aecore/config/dev3.exs
  apps/aecore/config/prod.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/chain/difficulty.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/hashcash.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/header.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_difficulty_test.exs
  apps/aecore/test/aecore_hashcash_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_pool_controller.ex
  apps/aeutil/lib/bits.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
  mix.exs
  mix.lock
Labels: spec-adjust, structures

#298 [GH-#297] initialize unknown accounts empty, fixed undefined function
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
Labels: bug, non-spec

#301 [GH-#257] Adjusted block serialization/deserialization
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: spec-adjust, structures

#291 [GH-#280] Changes the from_acc, to_acc and value fields
  README.md
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/data_tx.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
  apps/aecore/lib/aecore/structures/transaction.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aecore/test/aecore_chain_state_test.exs.bak
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_pool_controller.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: spec-adjust, structures

#293 [GH-#265] Making credo more strict and fixing the issues
  .credo.exs
  apps/aecore/lib/aecore.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/chain/difficulty.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/chain/worker/supervisor.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/miner/worker/supervisor.ex
  apps/aecore/lib/aecore/peers/peer_blocks_task.ex
  apps/aecore/lib/aecore/peers/scheduler.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/peers/worker/supervisor.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/persistence/worker/supervisor.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/hashcash.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/block.ex
  apps/aecore/lib/aecore/structures/transaction.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aecore/lib/aecore/txs/pool/worker/supervisor.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/lib/aecore/wallet/worker/supervisor.ex
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/config/dev.exs
  apps/aehttpserver/lib/aehttpserver/application.ex
  apps/aehttpserver/lib/aehttpserver/web/channels/notification_channel.ex
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/plugs/authorization.ex
  apps/aehttpserver/lib/aehttpserver/web/plugs/set_header.ex
  apps/aeutil/lib/bits.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: enhancement, low-priority, non-spec

#310 [GH-309] Removing unnecessary code from sync.ex
  apps/aecore/lib/aecore/peers/sync.ex
Labels: bug, non-spec

#312 [GH-#311] Fixed wrong GenServer handle call atom
  apps/aecore/lib/aecore/peers/sync.ex
Labels: bug, non-spec

#316 [GH-#296] Fixing the transasction pattern matching problem in chain_state
  apps/aecore/lib/aecore/chain/worker.ex
Labels: bug, non-spec

#212 [GH-#172] Oracles
  README.md
  apps/aecore/config/dev.exs
  apps/aecore/config/dev1.exs
  apps/aecore/config/dev2.exs
  apps/aecore/config/dev3.exs
  apps/aecore/config/prod.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/chain/difficulty.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/hashcash.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/data_tx.ex
  apps/aecore/lib/aecore/structures/header.ex
  apps/aecore/lib/aecore/structures/oracle_extend_tx.ex
  apps/aecore/lib/aecore/structures/oracle_query_tx.ex
  apps/aecore/lib/aecore/structures/oracle_registration_tx.ex
  apps/aecore/lib/aecore/structures/oracle_response_tx.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
  apps/aecore/lib/aecore/structures/transaction.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/mix.exs
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/oracle_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/endpoint.ex
  apps/aehttpserver/lib/aehttpserver/web/router.ex
  apps/aeutil/lib/serialization.ex
  mix.exs
  mix.lock
Labels: spec-feature

#315 [GH-313] Fixed HTTP server endpoint bug
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
Labels: bug, non-spec
