Repository aeternity/elixir-node, pull requests merged in 2018-04, with the labels that each got.

#330 [GH-#282] Adjusted transaction json serialization
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_controller.ex
  apps/aeutil/lib/serialization.ex
Labels: spec-adjust, structures

#327 [GH-#303] refactor fee deduction update to be in data tx
  apps/aecore/lib/aecore/structures/data_tx.ex
  apps/aecore/test/aecore_tx_test.exs
Labels: enhancement, non-spec

#342 [GH-#338] Fixed the dev port
  apps/aehttpserver/config/dev.exs
Labels: enhancement, non-spec

#317 [GH-#252] Extract state structure handling
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chain_state.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/structures/account.ex
  apps/aecore/lib/aecore/structures/account_state_tree.ex
  apps/aecore/lib/aecore/structures/chainstate.ex
  apps/aecore/lib/aecore/structures/data_tx.ex
  apps/aecore/lib/aecore/structures/oracle_extend_tx.ex
  apps/aecore/lib/aecore/structures/oracle_query_tx.ex
  apps/aecore/lib/aecore/structures/oracle_registration_tx.ex
  apps/aecore/lib/aecore/structures/oracle_response_tx.ex
  apps/aecore/lib/aecore/structures/signed_tx.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
  apps/aecore/lib/aecore/structures/transaction.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aecore/test/test_utils.ex
  apps/aeutil/lib/serialization.ex
  mix.lock
Labels: chain-state, spec-adjust

#323 [GH-#322, GH-#261] Epoch gossip API, adjust timestamp validation
  README.md
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/header_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/new_tx_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/router.ex
  apps/aeutil/lib/http_util.ex
Labels: spec-adjust

#348 [GH-#332] Fixed Credo issues and made Travis to check credo
  .credo.exs
  .travis.yml
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/structures/chainstate.ex
  apps/aecore/lib/aecore/structures/oracle_extend_tx.ex
  apps/aecore/lib/aecore/structures/oracle_query_tx.ex
  apps/aecore/lib/aecore/structures/oracle_registration_tx.ex
  apps/aecore/lib/aecore/structures/oracle_response_tx.ex
  apps/aecore/lib/aecore/structures/spend_tx.ex
  apps/aecore/lib/aecore/txs/pool/worker.ex
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/test_utils.ex
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aeutil/lib/http_util.ex
  apps/aeutil/lib/scientific.ex
  apps/aeutil/lib/serialization.ex
Labels: enhancement, non-spec

#328 [GH-321] Moved all modules from Structures
  .iex.exs
  apps/aecore/lib/aecore.ex
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/difficulty.ex
  apps/aecore/lib/aecore/chain/header.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/hashcash.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/pool/worker/supervisor.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_difficulty_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_hashcash_test.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/new_tx_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/oracle_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_pool_controller.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: enhancement, non-spec, structures

#334 [GH-#269] Replace sha256 with blake2 for Oracles
  .travis.yml
  Dockerfile
  README.md
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aeutil/lib/hash.ex
  mix.exs
  mix.lock
Labels: spec-adjust, util

#331 [GH-#260] Added minimum fee
  apps/aecore/config/dev.exs
  apps/aecore/config/dev1.exs
  apps/aecore/config/dev2.exs
  apps/aecore/config/dev3.exs
  apps/aecore/config/prod.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
Labels: spec-adjust, util

#333 [GH-#325] check byte sizes for transactions
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/test/aecore_tx_test.exs
Labels: enhancement, low-priority, non-spec

#337 [GH-#283] Adjusted transaction fields encoding
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aeutil/lib/serialization.ex
Labels: spec-adjust, structures

#351 [GH-#346] Add height of last update to one accounts state
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/multiple_transactions_test.exs
Labels: chain-state, spec-adjust

#358 [GH-#356] Adeed target to difficulty calculation
  apps/aeutil/lib/scientific.ex
  apps/aeutil/test/aeutil_scientific_test.exs
Labels: spec-adjust, util

#343 [GH-#329] Removed try/catch statements and refactored error handiling
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/header.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/pow/hashcash.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_peers_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aeutil/lib/parser.ex
  apps/aeutil/lib/serialization.ex
Labels: enhancement, non-spec

#361 [GH-#360] Removed the struct from the maps when checked for empty
  apps/aecore/lib/aecore/chain/worker.ex
Labels: bug
