Repository aeternity/elixir-node, pull requests merged in 2018-09, with the labels that each got.

#577 [GH-575-new] Fixed order of transaction root hash in calculating
  apps/aecore/lib/aecore/chain/chainstate.ex
Labels: spec-adjust

#580 [GH-579] Added name_claim_burned_fee and fixed total fee of NameClaimTx
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
Labels: spec-adjust

#567 [GH-524] Rewrite Sync module
  .iex.exs
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/peers/jobs.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker/supervisor.ex
  apps/aecore/lib/aecore/sync/chain.ex
  apps/aecore/lib/aecore/sync/jobs.ex
  apps/aecore/lib/aecore/sync/sync.ex
  apps/aecore/lib/aecore/sync/task.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_peer_rlp_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aecore/test/aecore_target_test.exs
Labels: enhancement, spec-adjust

#585 [GH-578] removed incorrect gb_merkle_tree proofs
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/mix.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_controller.ex
Labels: enhancement, non-spec

#589 [GH-588] Adjusted oracle transactions
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/test/aecore_oracle_test.exs
  apps/aetestframework/lib/worker.ex
Labels: spec-adjust

#595 [GH-593] Fixed name_update_tx
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
Labels: spec-adjust

#605 [GH-505] replace deprecated supervisor.spec
  apps/aecore/test/aecore_channels_test.exs
  apps/aehttpserver/lib/aehttpserver/aehttpserver.ex
  apps/aehttpserver/lib/aehttpserver/application.ex
  apps/aehttpserver/mix.exs
Labels: enhancement, non-spec

#606 [GH-352] Fix merge issue in oracles
  apps/aecore/lib/aecore/oracle/oracle_query.ex
Labels: bug

#608 [GH-584] Improved function specs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/genesis.ex
  apps/aecore/lib/aecore/chain/header.ex
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/chain/target.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/channel/channel_state_off_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/contract/call.ex
  apps/aecore/lib/aecore/contract/call_state_tree.ex
  apps/aecore/lib/aecore/contract/contract.ex
  apps/aecore/lib/aecore/contract/contract_state_tree.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/naming/name.ex
  apps/aecore/lib/aecore/naming/name_commitment.ex
  apps/aecore/lib/aecore/naming/name_util.ex
  apps/aecore/lib/aecore/naming/naming_state_tree.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/oracle_query.ex
  apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aeutil/lib/bits.ex
  apps/aeutil/lib/scientific.ex
Labels: enhancement, non-spec

#612 [GH-607] Added Logger.error() if Peers.try_connect() fails
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/lib/aecore/peers/worker.ex
Labels: enhancement

#614 [GH-613] fix oracle relative/absolute tll incorrect functions
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
Labels: bug

#615 [GH-603] adjusted readme structure
  README.md
  docs/detailed-usage.md
  docs/developer-docs.md
Labels: enhancement

#618 [GH-603] readme adjustment suggestions
  README.md
Labels: enhancement

#625 #624 disable multi_node_sync_tests
  .travis.yml
  apps/aetestframework/test/multi_node_sync_test.exs
Labels: test

#619 [GH-609] Fixed Aeutil.PatriciaMerkleTree insert func
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/test/patricia_merkle_tree_test.exs
Labels: bug

#596 [GH-591] Make max txs per block be equal to epoch node
  apps/aecore/config/dev.exs
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aetestframework/lib/worker.ex
  apps/aetestframework/test/multi_node_sync_test.exs
Labels: spec-adjust

#630 [GH-545] added aeternity erlang compatibility doc
  README.md
  docs/aeternity-erlang-compatibility.md
Labels: documentation

#631 [GH-626] removed top_block reference from validation
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  mix.lock
Labels: bug
