Repository aeternity/elixir-node, pull requests merged in 2018-10, with the labels that each got.

#636 [GH-632] remove chain usage from oracle_query_tx
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
Labels: bug

#649 [GH-640] Added check if txs minimum fees are met when validating a block
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
Labels: bug

#658 [GH-657] add make all-test target, to locally run checks done by ci
  .dockerignore
  .gitignore
  Makefile
Labels: test

#653 [GH-652] Automatically added spend_tx and naming txs to the pool upon creation
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_naming_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aecore/test/test_utils.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aetestframework/lib/worker.ex
Labels: enhancement, non-spec

#651 [GH-633, GH-634, GH-641, GH-643, GH-650] Various oracle related adjustments
  apps/aecore/config/dev.exs
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/test/aecore_oracle_test.exs
Labels: bug, enhancement

#665 [GH-635][GH-659] use is_minimum_fee_met callback for all transactions implicitly
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
Labels: chain-state, enhancement

#663 [GH-656] Adjusted code duplication between state trees
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/channel/channel_state_tree.ex
  apps/aecore/lib/aecore/contract/call_state_tree.ex
  apps/aecore/lib/aecore/contract/contract_state_tree.ex
  apps/aecore/lib/aecore/naming/name.ex
  apps/aecore/lib/aecore/naming/name_commitment.ex
  apps/aecore/lib/aecore/naming/naming_state_tree.ex
  apps/aecore/lib/aecore/util/state_trees.ex
  apps/aecore/test/aecore_contract_test.exs
Labels: enhancement, non-spec

#673 [GH-671] Fixed sync with 3 or more nodes
  apps/aecore/lib/aecore/sync/sync.ex
Labels: bug

#586 [GH-533] Channel adjustments
  .iex.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/channel/channel_off_chain_tx.ex
  apps/aecore/lib/aecore/channel/channel_off_chain_update.ex
  apps/aecore/lib/aecore/channel/channel_state_off_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/channel/channel_state_tree.ex
  apps/aecore/lib/aecore/channel/channel_transaction.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/channel/updates/channel_create_update.ex
  apps/aecore/lib/aecore/channel/updates/channel_deposit_update.ex
  apps/aecore/lib/aecore/channel/updates/channel_transfer_update.ex
  apps/aecore/lib/aecore/channel/updates/channel_widthdraw_update.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/lib/aecore/keys/keys.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/poi/poi.ex
  apps/aecore/lib/aecore/poi/poi_persistence.ex
  apps/aecore/lib/aecore/poi/poi_proof.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_channels_compatibility_test.exs
  apps/aecore/test/aecore_channels_test.exs
  apps/aecore/test/aecore_poi_epoch_compatibility_and_functional_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_pool_controller.ex
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/lib/type_to_tag.ex
  apps/aeutil/test/patricia_merkle_tree_test.exs
Labels: spec-adjust, structures

#662 [GH-638] Channel compatibility testing docs
  docs/aeternity-erlang-compatibility.md
Labels: channel, documentation

#682 [GH-681] Updated aeternity-erlang-compatibility documentation
  docs/aeternity-erlang-compatibility.md
Labels: documentation, enhancement

#684 [GH-683] Fixed error message when Peers.try_connect()
  apps/aecore/lib/aecore/peers/worker.ex
Labels: enhancement

#679 [GH-645] Identifier types are now checked when processing transactions
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
Labels: bug, spec-adjust

#688 [GH-687] always recompile project in CI, fix compile errors
  .travis.yml
  apps/aetestframework/mix.exs
Labels: bug, test

#670 [GH-669] Channels compatiblity tests
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/test/aecore_channels_compatibility_test.exs
  docs/aeternity-erlang-compatibility.md
Labels: channel, test

#689 [GH-685] Added additional identifier checks
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
Labels: enhancement, non-spec

#680 [GH-598] Introducing a Rox DB supplier.
  apps/aecore/lib/aecore/persistence/supplier.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/persistence/worker/supervisor.ex
Labels: enhancement, non-spec

#690 [GH-602] Testframework stability fixes
  Makefile
  apps/aetestframework/lib/utils.ex
  apps/aetestframework/lib/worker.ex
  apps/aetestframework/mix.exs
  apps/aetestframework/test/multi_node_sync_test.exs
Labels: test

#694 [GH-693] Check if code is formatted in travis
  .travis.yml
  apps/aetestframework/mix.exs
Labels: discussion

#696 [GH-695] Upgraded ex_rlp to 0.3.0
  apps/aecore/mix.exs
  apps/aeutil/mix.exs
  mix.exs
  mix.lock
Labels: enhancement, non-spec

#617 [GH-602] Refactoring Multinode sync test Framework and it's tests
  .formatter.exs
  Makefile
  README.md
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aetestframework/lib/utils.ex
  apps/aetestframework/lib/worker.ex
  apps/aetestframework/lib/worker/supervisor.ex
  apps/aetestframework/mix.exs
  apps/aetestframework/test/multi_node_sync_test.exs
Labels: enhancement, non-spec

#621 [GH-538] Stateful Contracts
  .travis.yml
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/contract/call.ex
  apps/aecore/lib/aecore/contract/call_state_tree.ex
  apps/aecore/lib/aecore/contract/contract.ex
  apps/aecore/lib/aecore/contract/contract_constants.ex
  apps/aecore/lib/aecore/contract/contract_state_tree.ex
  apps/aecore/lib/aecore/contract/dispatch.ex
  apps/aecore/lib/aecore/contract/tx/contract_call_tx.ex
  apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
  apps/aecore/lib/aecore/contract/vm_chain.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/mix.exs
  apps/aecore/test/aecore_contract_test.exs
  apps/aeutil/lib/type_to_tag.ex
  apps/aevm/lib/aevm.ex
  apps/aevm/lib/aevm_const.ex
  apps/aevm/lib/aevm_util.ex
  apps/aevm/lib/chain_api.ex
  apps/aevm/lib/gas.ex
  apps/aevm/lib/gas_codes.ex
  apps/aevm/lib/memory.ex
  apps/aevm/lib/op_codes.ex
  apps/aevm/lib/op_codes_util.ex
  apps/aevm/lib/stack.ex
  apps/aevm/lib/state.ex
  apps/aevm/lib/storage.ex
  apps/aevm/test/aevm_test.exs
  apps/aevm/test/ethereum_test_chain.ex
  mix.exs
  mix.lock
Labels: aevm

#706 [GH-700] Made contract create tx compatible to Epoch protocol.
  apps/aecore/lib/aecore/contract/call.ex
  apps/aecore/lib/aecore/contract/dispatch.ex
  apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
Labels: 0.16, bug, spec-adjust

#710 [GH-709] Remove reference to Chain.chain_state() in ContractCallTx
  apps/aecore/lib/aecore/contract/tx/contract_call_tx.ex
  apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
Labels: chain-state

#711 [GH-707] Adjust contract_call_tx function
  apps/aecore/lib/aecore/contract/tx/contract_call_tx.ex
  apps/aecore/test/aecore_contract_test.exs
  apps/aevm/lib/aevm.ex
Labels: bug, spec-adjust

#697 [GH-490] Channel withdraw and deposit
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/channel/channel_off_chain_tx.ex
  apps/aecore/lib/aecore/channel/channel_off_chain_update.ex
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/channel/channel_transaction.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_deposit_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_withdraw_tx.ex
  apps/aecore/lib/aecore/channel/updates/channel_deposit_update.ex
  apps/aecore/lib/aecore/channel/updates/channel_withdraw_update.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/lib/aecore/poi/poi.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/lib/aecore/util/serializable.ex
  apps/aecore/test/aecore_channels_test.exs
  apps/aecore/test/test_utils.ex
  apps/aeutil/lib/type_to_tag.ex
  docs/aeternity-erlang-compatibility.md
  docs/detailed-usage.md
Labels: channel, spec-adjust
