Repository aeternity/elixir-node, pull requests merged in 2018-06, with the labels that each got.

#403 [GH-#402] Refactored Target code
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/target.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_target_test.exs
  apps/aecore/test/aecore_validation_test.exs
  dialyzer.ignore-warnings
Labels: non-spec, util

#404 [GH-#396] Fix incorrect function specifications
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/naming/naming.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aehttpclient/lib/client.ex
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/miner_controller.ex
  apps/aeutil/lib/serialization.ex
  dialyzer.ignore-warnings
Labels: enhancement, non-spec

#409 [GH-#408] removed halt-exit-status for dialyzer in travis.yml
  .travis.yml
  dialyzer.ignore-warnings
Labels: enhancement, non-spec

#405 [GH-#341] use patricia merkle tree as accounts_state merkle tree implementation
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/lib/serialization.ex
  dialyzer.ignore-warnings
Labels: chain-state, spec-adjust

#407 [GH-#401] Made adjustments to header related serializations
  apps/aecore/config/config.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aeutil/lib/serialization.ex
  dialyzer.ignore-warnings
Labels: spec-adjust, structures

#412 [GH-#406] Removed last_updated field from Account structure
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aecore/test/multiple_transactions_test.exs
Labels: spec-adjust, structures

#410 [GH-#369] Represent naming state using PMT
  .iex.exs
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/naming/naming_state_tree.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_naming_test.exs
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/lib/serialization.ex
Labels: chain-state, spec-adjust

#418 [GH-#416] Added ttl fields to all transactions, RLP adjustments
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: spec-adjust, structures

#420 [GH-#370] Pretty print of given PMT
  .iex.exs
  apps/aeutil/lib/patricia_merkle_tree.ex
Labels: chain-state, enhancement, non-spec

#423 [GH-#422] Reordered and adjusted pattern-matching bindings in DataTx rlp decodings
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/test/aecore_serializations_test.exs
Labels: bug

#399 [GH-#364] New peer connections using TCP & noise
  .iex.exs
  .travis.yml
  Dockerfile
  README.md
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore.ex
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/header.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/keys/peer.ex
  apps/aecore/lib/aecore/keys/utils.ex
  apps/aecore/lib/aecore/keys/wallet.ex
  apps/aecore/lib/aecore/keys/worker.ex
  apps/aecore/lib/aecore/keys/worker/supervisor.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/naming/naming.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/peers/peer_blocks_task.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/lib/aecore/peers/scheduler.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/peers/worker/peer_connection_supervisor.ex
  apps/aecore/lib/aecore/peers/worker/supervisor.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/mix.exs
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_naming_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_peers_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/router.ex
  dialyzer.ignore-warnings
  docker-compose.yml
  mix.exs
  mix.lock
Labels: spec-feature, sync

#431 [GH-#430] fix broken /balance endpoint
  apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex
Labels: bug

#439 [GH-#438] Fixed wallet dependency to use a specific ref
  mix.exs
  mix.lock
Labels: bug, non-spec

#437 [GH-#434] remove unused files
  apps/aecore/.gitignore
  apps/aecore/README.md
  apps/aehttpclient/.gitignore
  apps/aehttpclient/README.md
  apps/aehttpserver/.gitignore
  apps/aehttpserver/README.md
Labels: enhancement, non-spec

#436 [GH-#435] clean config files
  apps/aecore/config/dev1.exs
  apps/aecore/config/dev2.exs
  apps/aecore/config/dev3.exs
  apps/aecore/config/prod.exs
  apps/aecore/config/test.exs
  apps/aehttpserver/config/dev1.exs
  apps/aehttpserver/config/dev2.exs
  apps/aehttpserver/config/dev3.exs
Labels: enhancement, non-spec

#444 [GH-#353] fix unreachable xrefs and added to travis
  .travis.yml
  apps/aecore/lib/aecore/tx/pool/worker.ex
Labels: non-spec, test
