Repository aeternity/elixir-node, pull requests merged in 2018-07, with the labels that each got.

#414 [GH-#359] Building a new Sync implementation using the Noise protocol
  .iex.exs
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/target.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/keys/peer.ex
  apps/aecore/lib/aecore/peers/events.ex
  apps/aecore/lib/aecore/peers/jobs.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/peers/worker.ex
  apps/aecore/lib/aecore/peers/worker/supervisor.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/mix.exs
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aeutil/lib/serialization.ex
  dialyzer.ignore-warnings
  mix.exs
  mix.lock
Labels: spec-adjust, sync

#448 [GH-#421] Persisting chainstates by given block hash
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/test/aecore_persistence_test.exs
Labels: bug

#452 [GH-#442] extracted governance constants
  .credo.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/target.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/naming/name_util.ex
  apps/aecore/lib/aecore/naming/naming.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
Labels: enhancement, non-spec

#463 [GH-#460] Fixed wrong AccountStateTree.get/2 specification
  apps/aecore/lib/aecore/account/account_state_tree.ex
Labels: bug

#464 [GH-#455] Fixed NameUpdateTx RLP decoding
  apps/aecore/lib/aecore/tx/data_tx.ex
Labels: bug, spec-adjust

#426 [GH-#349] Represent oracles state as PMT
  .credo.exs
  .iex.exs
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/oracle_controller.ex
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/lib/serialization.ex
  mix.exs
  mix.lock
Labels: chain-state, spec-adjust

#457 [GH-#456] adjust multinode and clean helper in makefile
  Makefile
  apps/aecore/config/dev1.exs
  apps/aecore/config/dev2.exs
  apps/aecore/config/dev_build.exs
  apps/aehttpserver/config/dev1.exs
  apps/aehttpserver/config/dev2.exs
  apps/aehttpserver/config/dev3.exs
  apps/aehttpserver/config/dev_build.exs
  rel/config.exs
  rel/dev1/vm.args
  rel/dev2/vm.args
  rel/dev3/vm.args
Labels: enhancement, non-spec

#469 [GH-#468] Adjust oracles cache tree pruning functionality
  apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
Labels: bug, spec-adjust

#477 [GH-#476] simplify docker configuration
  .dockerignore
  Dockerfile
  Makefile
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aehttpclient/lib/client.ex
  docker-compose.yml
  docker/nginx-cors.conf
  docker/nginx-default.conf
Labels: non-spec, util

#479 [GH-#461] Fixed problem with getting account balance
  apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex
Labels: bug

#481 [GH-#480] Added function root_hash for Naming and Oracle Trees
  apps/aecore/lib/aecore/naming/naming_state_tree.ex
  apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
Labels: chain-state, spec-adjust

#478 [GH-#474] Improved oracle cache tree pruning functionality
  apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
Labels: spec-adjust

#484 [GH-#453] Root chainstate hash
  apps/aecore/lib/aecore/chain/chainstate.ex
Labels: chain-state, spec-adjust

#497 [GH-#488] Replace tx hash gb_tree with patricia merkle tree
  apps/aecore/lib/aecore/chain/block_validation.ex
  mix.exs
Labels: chain-state, spec-adjust

#392 [GH-#294] Channels
  .iex.exs
  README.md
  apps/aecore/lib/aecore.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/channel/channel_state_off_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/channel/channel_state_tree.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
  apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/lib/aecore/channel/worker/supervisor.ex
  apps/aecore/lib/aecore/peers/sync.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_channels_test.exs
  apps/aecore/test/test_utils.ex
  apps/aeutil/lib/events.ex
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/lib/serialization.ex
  dialyzer.ignore-warnings
Labels: spec-feature
