Repository aeternity/elixir-node, pull requests merged in 2018-08, with the labels that each got.

#496 [GH-#432] Introducing Binary Identifiers
  .iex.exs
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/identifier.ex
  apps/aecore/lib/aecore/naming/name_util.ex
  apps/aecore/lib/aecore/naming/naming.ex
  apps/aecore/lib/aecore/naming/naming_state_tree.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/test/aecore_channels_test.exs
  apps/aecore/test/aecore_naming_test.exs
  apps/aecore/test/aecore_peer_rlp_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_pool_controller.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: spec-adjust, spec-feature

#514 [GH-#498] Removed unused functions from http client
  apps/aehttpclient/lib/client.ex
Labels: enhancement, non-spec

#517 [GH-#516] Adjusted oracle structures
  README.md
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_serializations_test.exs
Labels: spec-adjust

#525 [GH-491] Channel snapshot
  README.md
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/channel/tx/channel_snapshot_solo_tx.ex
  apps/aecore/lib/aecore/channel/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_channels_test.exs
  apps/aeutil/lib/type_to_tag.ex
Labels: master-channels, spec-feature

#532 [GH-#510] Equalize the Genesis block structure with Epoch
  .iex.exs
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/config/genesis/accounts.json
  apps/aecore/config/prod.exs
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/genesis.ex
  apps/aecore/lib/aecore/chain/header.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/governance/genesis_constants.ex
  apps/aecore/lib/aecore/governance/governance_constants.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/test/aecore_hashcash_test.exs
  apps/aecore/test/aecore_target_test.exs
  apps/aecore/test/aecore_test_utils_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
Labels: spec-adjust, structures

#547 [GH-#546] Fixed p2p protocol verison
  apps/aecore/lib/aecore/peers/peer_connection.ex
Labels: spec-adjust

#549 [GH-#548] Fixed makefile signpeers directory name
  Makefile
Labels: bug, non-spec

#526 [GH-#507] Contracts and calls state trees
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/contract/call.ex
  apps/aecore/lib/aecore/contract/call_state_tree.ex
  apps/aecore/lib/aecore/contract/contract.ex
  apps/aecore/lib/aecore/contract/contract_state_tree.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/test/aecore_contract_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/lib/type_to_tag.ex
Labels: aevm, spec-feature

#557 [GH-#512] Transaction pool sync
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/peers/peer_connection.ex
  apps/aecore/test/aecore_peer_rlp_test.exs
Labels: spec-feature, sync

#566 [GH-529] Fixed wrong specifications
  apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
  apps/aecore/lib/aecore/channel/channel_state_peer.ex
  apps/aecore/lib/aecore/naming/name_commitment.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/oracle_query.ex
  apps/aeutil/mix.exs
  dialyzer.ignore-warnings
Labels: low-priority, non-spec

#570 [GH-569] changed peer atom for get_info_try_connect
  apps/aehttpserver/lib/aehttpserver/web/controllers/peers_controller.ex
Labels: bug

#572 [GH-571] Adjusted calculate_txs_hash logic
  apps/aecore/lib/aecore/chain/block_validation.ex
Labels: bug, spec-adjust
