Repository aeternity/elixir-node, pull requests merged in 2018-05, with the labels that each got.

#363 [GH-#362] adjust readme
  README.md
Labels: enhancement, non-spec

#350 [GH-#274] naming system
  .iex.exs
  README.md
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/naming/name_util.ex
  apps/aecore/lib/aecore/naming/naming.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/test/aecore_naming_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aeutil/lib/hash.ex
  apps/aeutil/lib/serialization.ex
  mix.exs
  mix.lock
Labels: spec-feature

#355 [GH-#228] CoinbaseTx, refactoring and multisig transactions
  .credo.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/account/tx/coinbase_tx.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
  apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
  apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
  apps/aecore/lib/aecore/persistence/worker.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/lib/aecore/wallet/worker.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_persistence_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/lib/client.ex
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/new_tx_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/oracle_controller.ex
  apps/aehttpserver/lib/aehttpserver/web/controllers/tx_pool_controller.ex
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
Labels: enhancement, non-spec, spec-feature

#384 [GH-#383] Reversed order of argument in deduct_fee function
  apps/aecore/lib/aecore/tx/data_tx.ex
Labels: bug

#397 [GH-#373] Getting all keys and their count of given patricia trie
  apps/aeutil/lib/patricia_merkle_tree.ex
  apps/aeutil/test/patricia_merkle_tree_test.exs
  dialyzer.ignore-warnings
  mix.lock
Labels: enhancement, non-spec

#394 [GH-#393] fixed nil.refs error
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/persistence/worker.ex
Labels: bug, non-spec

#387 [GH-#335, GH-#381] Introducing RLP encodings/decodings, adjusted Account and SpendTx structures.
  apps/aecore/config/config.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/account_state_tree.ex
  apps/aecore/lib/aecore/account/tx/spend_tx.ex
  apps/aecore/lib/aecore/chain/block.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/naming/naming.ex
  apps/aecore/lib/aecore/oracle/oracle.ex
  apps/aecore/lib/aecore/pow/cuckoo.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/pool/worker.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/test/aecore_chain_state_test.exs
  apps/aecore/test/aecore_get_txs_for_address.exs
  apps/aecore/test/aecore_naming_test.exs
  apps/aecore/test/aecore_oracle_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aecore/test/aecore_validation_test.exs
  apps/aecore/test/multiple_transactions_test.exs
  apps/aehttpclient/test/aehttpclient_test.exs
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
  dialyzer.ignore-warnings
  mix.exs
Labels: spec-adjust, structures

#400 [GH-#398] move coinbase to header
  apps/aecore/config/config.exs
  apps/aecore/config/dev.exs
  apps/aecore/config/dev1.exs
  apps/aecore/config/dev2.exs
  apps/aecore/config/dev3.exs
  apps/aecore/config/prod.exs
  apps/aecore/config/test.exs
  apps/aecore/lib/aecore/account/account.ex
  apps/aecore/lib/aecore/account/tx/coinbase_tx.ex
  apps/aecore/lib/aecore/chain/block_validation.ex
  apps/aecore/lib/aecore/chain/chainstate.ex
  apps/aecore/lib/aecore/chain/header.ex
  apps/aecore/lib/aecore/chain/worker.ex
  apps/aecore/lib/aecore/miner/worker.ex
  apps/aecore/lib/aecore/tx/data_tx.ex
  apps/aecore/lib/aecore/tx/signed_tx.ex
  apps/aecore/lib/aecore/tx/transaction.ex
  apps/aecore/test/aecore_chain_test.exs
  apps/aecore/test/aecore_miner_test.exs
  apps/aecore/test/aecore_pow_cuckoo_test.exs
  apps/aecore/test/aecore_serializations_test.exs
  apps/aecore/test/aecore_tx_test.exs
  apps/aecore/test/aecore_txs_pool_test.exs
  apps/aeutil/lib/serialization.ex
  apps/aeutil/test/aeutil_serialization_test.exs
  dialyzer.ignore-warnings
Labels: spec-adjust, structures
